#!groovy
// Check ub1 properties
properties([disableConcurrentBuilds()])

pipeline {
    agent {
        label 'test'
        }
    options {
        buildDiscarder(logRotator(numToKeepStr: '2', artifactNumToKeepStr: '2'))
        timestamps()
    }
    stages {
        stage("First step") {
            steps {
                sh "mvn clean test -Ddriver=remote -Ddriverurl=http://${remoteDriver}/wd/hub -Denv=P1"
            }
        }
        }
    }